### ISSUE TITLE
from dialogflow_v2 import AgentsClient ImportError: cannot import name AgentsClient

### ISSUE THREAD

**Issue by vinc3nt** [googleapis/dialogflow-python-client-v2#130]
I am new to dialogflow and python i tried to go through this api but whatever i try i get this error , i have been using the sample code provided and this is what i get at the end of my console 
Traceback (most recent call last):
  File "C:\Users\vin\Desktop\autoreply bets\efd.py", line 1, in <module>
    import dialogflow_v2 as dialogflow
  File "C:\Python27\lib\site-packages\dialogflow_v2\__init__.py", line 19, in <module>
    from dialogflow_v2 import types
  File "C:\Python27\lib\site-packages\dialogflow_v2\types.py", line 20, in <module>
    from google.api_core.protobuf_helpers import get_messages
  File "C:\Python27\lib\site-packages\google\api_core\__init__.py", line 20, in <module>
    from pkg_resources import get_distribution
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 3088, in <module>
    @_call_aside
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 3116, in _initialize_master_working_set
    for dist in working_set
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 3116, in <genexpr>
    for dist in working_set
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2639, in activate
    declare_namespace(pkg)
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2176, in declare_namespace
    _handle_ns(packageName, path_item)
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2111, in _handle_ns
    loader.load_module(packageName)
  File "C:\Python27\lib\pkgutil.py", line 243, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "C:\Users\vin\Desktop\autoreply bets\google.py", line 5, in <module>
    import dialogflow
  File "C:\Python27\lib\site-packages\dialogflow\__init__.py", line 17, in <module>
    from dialogflow_v2 import AgentsClient
ImportError: cannot import name AgentsClient

**Comment by nnegrey** [comment]
Which sample are you trying to run?

**Comment by vinc3nt** [comment]
I used this one on windows 8.1 tried it on both python 2.7 and 3 



import dialogflow_v2 as dialogflow
import argparse
import uuid
project_id="small-talk-yuqcnd"
session_id="4"
text="hi"
language_code="de"
session_client = dialogflow.SessionsClient()

session = session_client.session_path(project_id, session_id)
print('Session path: {}\n'.format(session))

for text in texts:
    text_input = dialogflow.types.TextInput(text=text, language_code=language_code)

    query_input = dialogflow.types.QueryInput(text=text_input)

    response = session_client.detect_intent(session=session, query_input=query_input)
    print('Fulfillment text: {}\n'.format(response.query_result.fulfillment_text))

**Comment by nnegrey** [comment]
What version of the library do you have?

```
pip freeze | grep dialogflow
```

**Comment by nnegrey** [comment]
Going to close this as there hasn't been a response lately, please feel free to re-open if you are still having an issue. :)
