### ISSUE TITLE
RegEx causing BadRequestException?

### ISSUE THREAD

**Issue by bscotty96** [googleapis/dialogflow-python-client-v2#165]
I am trying to list the entities on my Dialogflow project. what once previously worked, is now throwing an exception. The only change recently, has been the introduction of RegEx into the entities on Dialogflow.

#### Environment details

1. OS: Windows 10 Pro
2. Python: 3.6.6
3. Dialogflow Version: 0.7.2 - using dialogflow_v2beta1

I tried using the original example (below) but I still get the same error.

#### Code example
This example was copied from 
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/dialogflow/cloud-client/entity_type_management.py

```python
def list_entity_types(project_id):
    import dialogflow_v2 as dialogflow
    entity_types_client = dialogflow.EntityTypesClient()

    parent = entity_types_client.project_agent_path(project_id)

    entity_types = entity_types_client.list_entity_types(parent)

    for entity_type in entity_types:
        print('Entity type name: {}'.format(entity_type.name))
        print('Entity type display name: {}'.format(entity_type.display_name))
        print('Number of entities: {}\n'.format(len(entity_type.entities)))

```
The issue seems to come from the ```for entity_type in entity_types:``` line.

#### Stack trace
```
Traceback (most recent call last):
  File "C:\Users\bscotland\PycharmProjects\Speech_Betting\venv\lib\site-packages\google\api_core\grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "C:\Users\bscotland\PycharmProjects\Speech_Betting\venv\lib\site-packages\grpc\_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "C:\Users\bscotland\PycharmProjects\Speech_Betting\venv\lib\site-packages\grpc\_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "com.google.apps.framework.request.BadRequestException: Validate entity failed because of the following reasons: Regexp entity entry synonyms should be either empty or contain single synonym that equal to entry value.
Regexp entity entry synonyms should be either empty or contain single synonym that equal to entry value."
	debug_error_string = "{"created":"@1572947931.774000000","description":"Error received from peer ipv4:172.217.169.10:443","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"com.google.apps.framework.request.BadRequestException: Validate entity failed because of the following reasons: Regexp entity entry synonyms should be either empty or contain single synonym that equal to entry value.\nRegexp entity entry synonyms should be either empty or contain single synonym that equal to entry value.","grpc_status":3}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:/Users/bscotland/PycharmProjects/Speech_Betting/conversation/dialogflow_communication.py", line 204, in <module>
    raise e
  File "C:/Users/bscotland/PycharmProjects/Speech_Betting/conversation/dialogflow_communication.py", line 202, in <module>
    dft.set_current_entities()
  File "C:/Users/bscotland/PycharmProjects/Speech_Betting/conversation/dialogflow_communication.py", line 125, in set_current_entities
    for entity_type in entity_types:
  File "C:\Users\bscotland\PycharmProjects\Speech_Betting\venv\lib\site-packages\google\api_core\page_iterator.py", line 204, in _items_iter
    for page in self._page_iter(increment=False):
  File "C:\Users\bscotland\PycharmProjects\Speech_Betting\venv\lib\site-packages\google\api_core\page_iterator.py", line 235, in _page_iter
    page = self._next_page()
  File "C:\Users\bscotland\PycharmProjects\Speech_Betting\venv\lib\site-packages\google\api_core\page_iterator.py", line 526, in _next_page
    response = self._method(self._request)
  File "C:\Users\bscotland\PycharmProjects\Speech_Betting\venv\lib\site-packages\google\api_core\gapic_v1\method.py", line 143, in __call__
    return wrapped_func(*args, **kwargs)
  File "C:\Users\bscotland\PycharmProjects\Speech_Betting\venv\lib\site-packages\google\api_core\retry.py", line 277, in retry_wrapped_func
    on_error=on_error,
  File "C:\Users\bscotland\PycharmProjects\Speech_Betting\venv\lib\site-packages\google\api_core\retry.py", line 182, in retry_target
    return target()
  File "C:\Users\bscotland\PycharmProjects\Speech_Betting\venv\lib\site-packages\google\api_core\timeout.py", line 214, in func_with_timeout
    return func(*args, **kwargs)
  File "C:\Users\bscotland\PycharmProjects\Speech_Betting\venv\lib\site-packages\google\api_core\grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.InvalidArgument: 400 com.google.apps.framework.request.BadRequestException: Validate entity failed because of the following reasons: Regexp entity entry synonyms should be either empty or contain single synonym that equal to entry value.
Regexp entity entry synonyms should be either empty or contain single synonym that equal to entry value.
```
Any ideas on a fix? I am hoping that I will not have to change the entities away from RegEx!

**Comment by newtonmunene99** [comment]
Were your able to fix this?

**Comment by bscotty96** [comment]
No I still have the issue and it seems to be localised to regex only entities.

**Comment by newtonmunene99** [comment]
Go to your entity on Dialogflow and switch to Raw Editor Mode. Go to JSON tab and ensure that the regex value matches the synonym value. And it should not have more than one synonym

**Comment by bscotty96** [comment]
Thanks for the help! It is working now.
