### ISSUE TITLE
google.api_core.exceptions.PermissionDenied: 403 IAM permission 'dialogflow.sessions.detectIntent' on 'projects/None/agent' denied.

### ISSUE THREAD

**Issue by shreyasharma98** [googleapis/dialogflow-python-client-v2#180]
Facing this error while trying a customised frontend client Flask for dialogflow!

![Annotation 2020-03-16 130722](https://user-images.githubusercontent.com/35392800/76733833-9bc75800-6787-11ea-9c99-d24ee33bac2a.png)

Here's the code!
```
# /index.py
from flask import Flask, request, jsonify, render_template
import os
import dialogflow
import requests
import json
import pusher


pusher_client = pusher.Pusher(
        app_id=os.getenv('PUSHER_APP_ID'),
        key=os.getenv('PUSHER_KEY'),
        secret=os.getenv('PUSHER_SECRET'),
        cluster=os.getenv('PUSHER_CLUSTER'),
        ssl=True)

final = []
app = Flask(__name__)


@app.route('/')
def index():
    return render_template('index.html')

@app.route('/webhook', methods=['POST'])
def static_reply():
    string = "Hello there, this reply is from the webhook !! "
    my_result =  {"fulfillmentText": string, "source": string}
    return jsonify(my_result)
def detect_intent_texts(project_id, session_id, text, language_code):
    session_client = dialogflow.SessionsClient()
    session = session_client.session_path(project_id, session_id)
    
    if text:
        text_input = dialogflow.types.TextInput(
            text=text, language_code=language_code)
        query_input = dialogflow.types.QueryInput(text=text_input)
        response = session_client.detect_intent(
            session=session, query_input=query_input)
        
        return response.query_result.fulfillment_text


@app.route('/send_message', methods=['POST'])
def send_message():
    try:
        socketId = request.form['socketId']
    except KeyError:
        socketId = ''
        
    message = request.form['message']
    project_id = os.getenv('virtual-police-pmrtai')
    fulfillment_text = detect_intent_texts(project_id,, message, 'en')
    response_text = { "message":  fulfillment_text }

    pusher_client.trigger(
        'Virtual-Police', 
        'new_message', 
        {
            'human_message': message, 
            'bot_message': fulfillment_text,
        },
        socketId
    )
                        
    return jsonify(response_text)
# run Flask app
if __name__ == "__main__":
    app.run()
```

**Comment by shreyasharma98** [comment]
complete error statement -
```127.0.0.1 - - [16/Mar/2020 13:05:00] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [16/Mar/2020 13:05:03] "POST /send_message HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Users\Shreya\Anaconda3\lib\site-packages\google\api_core\grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "C:\Users\Shreya\Anaconda3\lib\site-packages\grpc\_channel.py", line 565, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "C:\Users\Shreya\Anaconda3\lib\site-packages\grpc\_channel.py", line 467, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
        status = StatusCode.PERMISSION_DENIED
        details = "IAM permission 'dialogflow.sessions.detectIntent' on 'projects/None/agent' denied."
        debug_error_string = "{"created":"@1584344103.812000000","description":"Error received from peer ipv4:172.217.161.10:443","file":"src/core/lib/surface/call.cc","file_line":1052,"grpc_message":"IAM permission 'dialogflow.sessions.detectIntent' on 'projects/None/agent' denied.","grpc_status":7}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Shreya\Anaconda3\lib\site-packages\flask\app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Shreya\Anaconda3\lib\site-packages\flask\app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Shreya\Anaconda3\lib\site-packages\flask\app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Shreya\Anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Shreya\Anaconda3\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Shreya\Anaconda3\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Shreya\Anaconda3\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Shreya\Anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Shreya\Anaconda3\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Shreya\Anaconda3\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Shreya\Desktop\Virtual_cop\index.py", line 53, in send_message
    fulfillment_text = detect_intent_texts(project_id, "unique", message, 'en')
  File "C:\Users\Shreya\Desktop\Virtual_cop\index.py", line 39, in detect_intent_texts
    session=session, query_input=query_input)
  File "C:\Users\Shreya\Anaconda3\lib\site-packages\dialogflow_v2\gapic\sessions_client.py", line 323, in detect_intent
    request, retry=retry, timeout=timeout, metadata=metadata
  File "C:\Users\Shreya\Anaconda3\lib\site-packages\google\api_core\gapic_v1\method.py", line 143, in __call__
    return wrapped_func(*args, **kwargs)
  File "C:\Users\Shreya\Anaconda3\lib\site-packages\google\api_core\retry.py", line 286, in retry_wrapped_func
    on_error=on_error,
  File "C:\Users\Shreya\Anaconda3\lib\site-packages\google\api_core\retry.py", line 184, in retry_target
    return target()
  File "C:\Users\Shreya\Anaconda3\lib\site-packages\google\api_core\timeout.py", line 214, in func_with_timeout
    return func(*args, **kwargs)
  File "C:\Users\Shreya\Anaconda3\lib\site-packages\google\api_core\grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
    # Permission is hereby granted, free of charge, to any person obtaining a copy
google.api_core.exceptions.PermissionDenied: 403 IAM permission 'dialogflow.sessions.detectIntent' on 'projects/None/agent' denied. 
```

**Comment by nnegrey** [comment]
Question: did you redact the `project-id` or is it actually `None`?

How do you configure auth? Environment variable to you Service Account's JSON key?

**Comment by sizrar** [comment]
I had the same issue, which was solved by exporting the GOOGLE_APPLICATION_CREDENTIALS to my python script: 

> export GOOGLE_APPLICATION_CREDENTIALS='path/to/google-credentials.json' 
> python bot.py 

I also tested without exporting the env var and instead, from within my python script 

>import os
>...
>os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = './google-credentials.json'

it works as well. (in a new shell) 
So  GOOGLE_APPLICATION_CREDENTIALS env var must be set to the right file one way or another.

**Comment by timkofu** [comment]
@nnegrey I have tried to use both the env var and the json file, doesn't work. Service account is set to Owner as directed [in the docs](https://cloud.google.com/dialogflow/docs/quick/setup).
